# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_MainWindow.ui'
#
# Created: Wed Apr 22 00:48:53 2015
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1036, 712)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideMiddle)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_viewLibrary = QtWidgets.QWidget()
        self.tab_viewLibrary.setObjectName("tab_viewLibrary")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_viewLibrary)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_viewLibrary)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 964, 588))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.tab_viewLibrary, "")
        self.tab_addPhoto = QtWidgets.QWidget()
        self.tab_addPhoto.setObjectName("tab_addPhoto")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_addPhoto)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_loadImage = QtWidgets.QPushButton(self.tab_addPhoto)
        self.btn_loadImage.setAutoDefault(True)
        self.btn_loadImage.setDefault(True)
        self.btn_loadImage.setObjectName("btn_loadImage")
        self.horizontalLayout_3.addWidget(self.btn_loadImage)
        self.ckbox_scrollMode = QtWidgets.QCheckBox(self.tab_addPhoto)
        self.ckbox_scrollMode.setChecked(True)
        self.ckbox_scrollMode.setTristate(False)
        self.ckbox_scrollMode.setObjectName("ckbox_scrollMode")
        self.horizontalLayout_3.addWidget(self.ckbox_scrollMode)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.scrollArea_leftPhoto = QtWidgets.QScrollArea(self.tab_addPhoto)
        self.scrollArea_leftPhoto.setWidgetResizable(True)
        self.scrollArea_leftPhoto.setObjectName("scrollArea_leftPhoto")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 403, 776))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lb_oriFilename = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.lb_oriFilename.setObjectName("lb_oriFilename")
        self.horizontalLayout_2.addWidget(self.lb_oriFilename)
        self.lb_oriSize = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.lb_oriSize.setObjectName("lb_oriSize")
        self.horizontalLayout_2.addWidget(self.lb_oriSize)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.lb_oriImage = ImageLabel(self.scrollAreaWidgetContents_2)
        self.lb_oriImage.setMinimumSize(QtCore.QSize(250, 250))
        self.lb_oriImage.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lb_oriImage.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_oriImage.setObjectName("lb_oriImage")
        self.verticalLayout_3.addWidget(self.lb_oriImage)
        self.lb_oriComponents = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.lb_oriComponents.setObjectName("lb_oriComponents")
        self.verticalLayout_3.addWidget(self.lb_oriComponents)
        self.txedt_oriComponents = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txedt_oriComponents.sizePolicy().hasHeightForWidth())
        self.txedt_oriComponents.setSizePolicy(sizePolicy)
        self.txedt_oriComponents.setObjectName("txedt_oriComponents")
        self.verticalLayout_3.addWidget(self.txedt_oriComponents)
        self.lb_oriQuantTbls = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.lb_oriQuantTbls.setObjectName("lb_oriQuantTbls")
        self.verticalLayout_3.addWidget(self.lb_oriQuantTbls)
        self.txedt_oriQuantTbls = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.txedt_oriQuantTbls.setObjectName("txedt_oriQuantTbls")
        self.verticalLayout_3.addWidget(self.txedt_oriQuantTbls)
        self.lb_oriHuffTbls = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.lb_oriHuffTbls.setObjectName("lb_oriHuffTbls")
        self.verticalLayout_3.addWidget(self.lb_oriHuffTbls)
        self.txedt_oriHuffTbls = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.txedt_oriHuffTbls.setObjectName("txedt_oriHuffTbls")
        self.verticalLayout_3.addWidget(self.txedt_oriHuffTbls)
        self.scrollArea_leftPhoto.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_5.addWidget(self.scrollArea_leftPhoto)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.btn_encrypt = QtWidgets.QPushButton(self.tab_addPhoto)
        self.btn_encrypt.setEnabled(False)
        self.btn_encrypt.setObjectName("btn_encrypt")
        self.verticalLayout_5.addWidget(self.btn_encrypt)
        self.btn_saveToLibrary = QtWidgets.QPushButton(self.tab_addPhoto)
        self.btn_saveToLibrary.setEnabled(False)
        self.btn_saveToLibrary.setCheckable(False)
        self.btn_saveToLibrary.setFlat(False)
        self.btn_saveToLibrary.setObjectName("btn_saveToLibrary")
        self.verticalLayout_5.addWidget(self.btn_saveToLibrary)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.scrollArea_rightPhoto = QtWidgets.QScrollArea(self.tab_addPhoto)
        self.scrollArea_rightPhoto.setWidgetResizable(True)
        self.scrollArea_rightPhoto.setObjectName("scrollArea_rightPhoto")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 402, 776))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lb_dstFilename = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.lb_dstFilename.setObjectName("lb_dstFilename")
        self.horizontalLayout_4.addWidget(self.lb_dstFilename)
        self.lb_dstSize = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.lb_dstSize.setObjectName("lb_dstSize")
        self.horizontalLayout_4.addWidget(self.lb_dstSize)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.lb_dstImage = ImageLabel(self.scrollAreaWidgetContents_3)
        self.lb_dstImage.setMinimumSize(QtCore.QSize(250, 250))
        self.lb_dstImage.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lb_dstImage.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_dstImage.setObjectName("lb_dstImage")
        self.verticalLayout_4.addWidget(self.lb_dstImage)
        self.lb_dstComponents = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.lb_dstComponents.setObjectName("lb_dstComponents")
        self.verticalLayout_4.addWidget(self.lb_dstComponents)
        self.txedt_dstComponents = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txedt_dstComponents.sizePolicy().hasHeightForWidth())
        self.txedt_dstComponents.setSizePolicy(sizePolicy)
        self.txedt_dstComponents.setObjectName("txedt_dstComponents")
        self.verticalLayout_4.addWidget(self.txedt_dstComponents)
        self.lb_dstQuantTbls = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.lb_dstQuantTbls.setObjectName("lb_dstQuantTbls")
        self.verticalLayout_4.addWidget(self.lb_dstQuantTbls)
        self.txedt_dstQuantTbls = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_3)
        self.txedt_dstQuantTbls.setObjectName("txedt_dstQuantTbls")
        self.verticalLayout_4.addWidget(self.txedt_dstQuantTbls)
        self.lb_dstHuffTbls = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.lb_dstHuffTbls.setObjectName("lb_dstHuffTbls")
        self.verticalLayout_4.addWidget(self.lb_dstHuffTbls)
        self.txedt_dstHuffTbls = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_3)
        self.txedt_dstHuffTbls.setObjectName("txedt_dstHuffTbls")
        self.verticalLayout_4.addWidget(self.txedt_dstHuffTbls)
        self.scrollArea_rightPhoto.setWidget(self.scrollAreaWidgetContents_3)
        self.horizontalLayout_5.addWidget(self.scrollArea_rightPhoto)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.tabWidget.addTab(self.tab_addPhoto, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(130, 160, 115, 32))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_3.setGeometry(QtCore.QRect(140, 230, 115, 32))
        self.pushButton_3.setObjectName("pushButton_3")
        self.graphicsView = QtWidgets.QGraphicsView(self.tab)
        self.graphicsView.setGeometry(QtCore.QRect(90, 330, 256, 192))
        self.graphicsView.setObjectName("graphicsView")
        self.widget = QtWidgets.QWidget(self.tab)
        self.widget.setGeometry(QtCore.QRect(380, 170, 258, 444))
        self.widget.setObjectName("widget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.textEdit = QtWidgets.QTextEdit(self.widget)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_6.addWidget(self.textEdit)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.textEdit_2 = QtWidgets.QTextEdit(self.widget)
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout_6.addWidget(self.textEdit_2)
        self.tabWidget.addTab(self.tab, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1036, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.pushButton_2.clicked.connect(self.textEdit.hide)
        self.pushButton_3.clicked.connect(self.textEdit.show)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SecretPhotos"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_viewLibrary), _translate("MainWindow", "Library"))
        self.btn_loadImage.setText(_translate("MainWindow", "Load Photo..."))
        self.ckbox_scrollMode.setText(_translate("MainWindow", "synchronous scroll"))
        self.label.setText(_translate("MainWindow", "Original"))
        self.lb_oriFilename.setText(_translate("MainWindow", "文件："))
        self.lb_oriSize.setText(_translate("MainWindow", "尺寸："))
        self.lb_oriImage.setText(_translate("MainWindow", "ImageLabel"))
        self.lb_oriComponents.setText(_translate("MainWindow", "颜色分量"))
        self.txedt_oriComponents.setDocumentTitle(_translate("MainWindow", "颜色分量"))
        self.txedt_oriComponents.setPlaceholderText(_translate("MainWindow", "颜色分量"))
        self.lb_oriQuantTbls.setText(_translate("MainWindow", "量化表"))
        self.lb_oriHuffTbls.setText(_translate("MainWindow", "哈夫曼表"))
        self.btn_encrypt.setText(_translate("MainWindow", "Encrypt =>"))
        self.btn_saveToLibrary.setText(_translate("MainWindow", "Save to Library"))
        self.label_2.setText(_translate("MainWindow", "Encrypted"))
        self.lb_dstFilename.setText(_translate("MainWindow", "文件："))
        self.lb_dstSize.setText(_translate("MainWindow", "尺寸："))
        self.lb_dstImage.setText(_translate("MainWindow", "ImageLabel"))
        self.lb_dstComponents.setText(_translate("MainWindow", "颜色分量"))
        self.txedt_dstComponents.setDocumentTitle(_translate("MainWindow", "颜色分量"))
        self.txedt_dstComponents.setPlaceholderText(_translate("MainWindow", "颜色分量"))
        self.lb_dstQuantTbls.setText(_translate("MainWindow", "量化表"))
        self.lb_dstHuffTbls.setText(_translate("MainWindow", "哈夫曼表"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_addPhoto), _translate("MainWindow", "Add Photo"))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_3.setText(_translate("MainWindow", "PushButton"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Page"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setStatusTip(_translate("MainWindow", "Quit SecretPhotos"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setStatusTip(_translate("MainWindow", "Open file..."))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+F"))

from ImageLabel import ImageLabel
