# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_MainWindow.ui'
#
# Created: Wed Apr 22 20:06:19 2015
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1036, 712)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideMiddle)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_viewLibrary = QtWidgets.QWidget()
        self.tab_viewLibrary.setObjectName("tab_viewLibrary")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_viewLibrary)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_viewLibrary)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 964, 588))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.tab_viewLibrary, "")
        self.tab_addPhoto = QtWidgets.QWidget()
        self.tab_addPhoto.setObjectName("tab_addPhoto")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_addPhoto)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_loadImage = QtWidgets.QPushButton(self.tab_addPhoto)
        self.btn_loadImage.setAutoDefault(True)
        self.btn_loadImage.setDefault(True)
        self.btn_loadImage.setObjectName("btn_loadImage")
        self.horizontalLayout_3.addWidget(self.btn_loadImage)
        self.ckbox_scrollMode = QtWidgets.QCheckBox(self.tab_addPhoto)
        self.ckbox_scrollMode.setChecked(True)
        self.ckbox_scrollMode.setTristate(False)
        self.ckbox_scrollMode.setObjectName("ckbox_scrollMode")
        self.horizontalLayout_3.addWidget(self.ckbox_scrollMode)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.scrollArea_leftPhoto = QtWidgets.QScrollArea(self.tab_addPhoto)
        self.scrollArea_leftPhoto.setWidgetResizable(True)
        self.scrollArea_leftPhoto.setObjectName("scrollArea_leftPhoto")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 403, 1091))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lb_oriFilename = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.lb_oriFilename.setWordWrap(True)
        self.lb_oriFilename.setObjectName("lb_oriFilename")
        self.horizontalLayout_2.addWidget(self.lb_oriFilename)
        self.lb_oriSize = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.lb_oriSize.setObjectName("lb_oriSize")
        self.horizontalLayout_2.addWidget(self.lb_oriSize)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.lb_oriImage = ImageLabel(self.scrollAreaWidgetContents_2)
        self.lb_oriImage.setMinimumSize(QtCore.QSize(250, 250))
        self.lb_oriImage.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lb_oriImage.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_oriImage.setObjectName("lb_oriImage")
        self.verticalLayout_3.addWidget(self.lb_oriImage)
        self.lb_oriComponents = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.lb_oriComponents.setObjectName("lb_oriComponents")
        self.verticalLayout_3.addWidget(self.lb_oriComponents)
        self.treeWidget_oriComponents = AdaptiveTreeWidget(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget_oriComponents.sizePolicy().hasHeightForWidth())
        self.treeWidget_oriComponents.setSizePolicy(sizePolicy)
        self.treeWidget_oriComponents.setUniformRowHeights(True)
        self.treeWidget_oriComponents.setHeaderHidden(False)
        self.treeWidget_oriComponents.setColumnCount(3)
        self.treeWidget_oriComponents.setObjectName("treeWidget_oriComponents")
        self.treeWidget_oriComponents.headerItem().setTextAlignment(0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.treeWidget_oriComponents.headerItem().setTextAlignment(1, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.treeWidget_oriComponents.header().setDefaultSectionSize(100)
        self.treeWidget_oriComponents.header().setSortIndicatorShown(False)
        self.verticalLayout_3.addWidget(self.treeWidget_oriComponents)
        self.lb_oriQuantTbls = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.lb_oriQuantTbls.setObjectName("lb_oriQuantTbls")
        self.verticalLayout_3.addWidget(self.lb_oriQuantTbls)
        self.treeWidget_oriQuantTbls = AdaptiveTreeWidget(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget_oriQuantTbls.sizePolicy().hasHeightForWidth())
        self.treeWidget_oriQuantTbls.setSizePolicy(sizePolicy)
        self.treeWidget_oriQuantTbls.setUniformRowHeights(True)
        self.treeWidget_oriQuantTbls.setObjectName("treeWidget_oriQuantTbls")
        self.verticalLayout_3.addWidget(self.treeWidget_oriQuantTbls)
        self.lb_oriHuffTbls = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.lb_oriHuffTbls.setObjectName("lb_oriHuffTbls")
        self.verticalLayout_3.addWidget(self.lb_oriHuffTbls)
        self.treeWidget_oriHuffTbls = AdaptiveTreeWidget(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget_oriHuffTbls.sizePolicy().hasHeightForWidth())
        self.treeWidget_oriHuffTbls.setSizePolicy(sizePolicy)
        self.treeWidget_oriHuffTbls.setUniformRowHeights(True)
        self.treeWidget_oriHuffTbls.setObjectName("treeWidget_oriHuffTbls")
        self.verticalLayout_3.addWidget(self.treeWidget_oriHuffTbls)
        self.scrollArea_leftPhoto.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_5.addWidget(self.scrollArea_leftPhoto)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.btn_encrypt = QtWidgets.QPushButton(self.tab_addPhoto)
        self.btn_encrypt.setEnabled(False)
        self.btn_encrypt.setObjectName("btn_encrypt")
        self.verticalLayout_5.addWidget(self.btn_encrypt)
        self.btn_saveToLibrary = QtWidgets.QPushButton(self.tab_addPhoto)
        self.btn_saveToLibrary.setEnabled(False)
        self.btn_saveToLibrary.setCheckable(False)
        self.btn_saveToLibrary.setFlat(False)
        self.btn_saveToLibrary.setObjectName("btn_saveToLibrary")
        self.verticalLayout_5.addWidget(self.btn_saveToLibrary)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.scrollArea_rightPhoto = QtWidgets.QScrollArea(self.tab_addPhoto)
        self.scrollArea_rightPhoto.setWidgetResizable(True)
        self.scrollArea_rightPhoto.setObjectName("scrollArea_rightPhoto")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 402, 1002))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lb_dstFilename = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.lb_dstFilename.setWordWrap(True)
        self.lb_dstFilename.setObjectName("lb_dstFilename")
        self.horizontalLayout_4.addWidget(self.lb_dstFilename)
        self.lb_dstSize = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.lb_dstSize.setObjectName("lb_dstSize")
        self.horizontalLayout_4.addWidget(self.lb_dstSize)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.lb_dstImage = ImageLabel(self.scrollAreaWidgetContents_3)
        self.lb_dstImage.setMinimumSize(QtCore.QSize(250, 250))
        self.lb_dstImage.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lb_dstImage.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_dstImage.setObjectName("lb_dstImage")
        self.verticalLayout_4.addWidget(self.lb_dstImage)
        self.lb_dstComponents = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.lb_dstComponents.setObjectName("lb_dstComponents")
        self.verticalLayout_4.addWidget(self.lb_dstComponents)
        self.treeWidget_dstComponents = AdaptiveTreeWidget(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget_dstComponents.sizePolicy().hasHeightForWidth())
        self.treeWidget_dstComponents.setSizePolicy(sizePolicy)
        self.treeWidget_dstComponents.setUniformRowHeights(True)
        self.treeWidget_dstComponents.setHeaderHidden(False)
        self.treeWidget_dstComponents.setColumnCount(3)
        self.treeWidget_dstComponents.setObjectName("treeWidget_dstComponents")
        self.treeWidget_dstComponents.headerItem().setTextAlignment(0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.treeWidget_dstComponents.headerItem().setTextAlignment(1, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.treeWidget_dstComponents.header().setDefaultSectionSize(100)
        self.treeWidget_dstComponents.header().setSortIndicatorShown(False)
        self.verticalLayout_4.addWidget(self.treeWidget_dstComponents)
        self.lb_dstQuantTbls = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.lb_dstQuantTbls.setObjectName("lb_dstQuantTbls")
        self.verticalLayout_4.addWidget(self.lb_dstQuantTbls)
        self.treeWidget_dstQuantTbls = AdaptiveTreeWidget(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget_dstQuantTbls.sizePolicy().hasHeightForWidth())
        self.treeWidget_dstQuantTbls.setSizePolicy(sizePolicy)
        self.treeWidget_dstQuantTbls.setUniformRowHeights(True)
        self.treeWidget_dstQuantTbls.setObjectName("treeWidget_dstQuantTbls")
        self.verticalLayout_4.addWidget(self.treeWidget_dstQuantTbls)
        self.lb_dstHuffTbls = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.lb_dstHuffTbls.setObjectName("lb_dstHuffTbls")
        self.verticalLayout_4.addWidget(self.lb_dstHuffTbls)
        self.treeWidget_dstHuffTbls = AdaptiveTreeWidget(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget_dstHuffTbls.sizePolicy().hasHeightForWidth())
        self.treeWidget_dstHuffTbls.setSizePolicy(sizePolicy)
        self.treeWidget_dstHuffTbls.setUniformRowHeights(True)
        self.treeWidget_dstHuffTbls.setObjectName("treeWidget_dstHuffTbls")
        self.verticalLayout_4.addWidget(self.treeWidget_dstHuffTbls)
        self.scrollArea_rightPhoto.setWidget(self.scrollAreaWidgetContents_3)
        self.horizontalLayout_5.addWidget(self.scrollArea_rightPhoto)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.tabWidget.addTab(self.tab_addPhoto, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.treeWidget = AdaptiveTreeWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        self.treeWidget.setMinimumSize(QtCore.QSize(0, 100))
        self.treeWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.verticalLayout_7.addWidget(self.treeWidget)
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit.setClearButtonEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_7.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_7.addWidget(self.pushButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem1)
        self.tabWidget.addTab(self.tab, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1036, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SecretPhotos"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_viewLibrary), _translate("MainWindow", "Library"))
        self.btn_loadImage.setText(_translate("MainWindow", "Load Photo..."))
        self.ckbox_scrollMode.setText(_translate("MainWindow", "synchronous scroll"))
        self.label.setText(_translate("MainWindow", "Original"))
        self.lb_oriFilename.setText(_translate("MainWindow", "文件："))
        self.lb_oriSize.setText(_translate("MainWindow", "尺寸："))
        self.lb_oriImage.setText(_translate("MainWindow", "ImageLabel"))
        self.lb_oriComponents.setText(_translate("MainWindow", "颜色分量"))
        self.treeWidget_oriComponents.setSortingEnabled(False)
        self.treeWidget_oriComponents.headerItem().setText(0, _translate("MainWindow", "ID"))
        self.treeWidget_oriComponents.headerItem().setText(1, _translate("MainWindow", "Property"))
        self.treeWidget_oriComponents.headerItem().setText(2, _translate("MainWindow", "Value"))
        self.lb_oriQuantTbls.setText(_translate("MainWindow", "量化表"))
        self.treeWidget_oriQuantTbls.headerItem().setText(0, _translate("MainWindow", "ID"))
        self.treeWidget_oriQuantTbls.headerItem().setText(1, _translate("MainWindow", "Property"))
        self.treeWidget_oriQuantTbls.headerItem().setText(2, _translate("MainWindow", "Value"))
        self.lb_oriHuffTbls.setText(_translate("MainWindow", "哈夫曼表"))
        self.treeWidget_oriHuffTbls.headerItem().setText(0, _translate("MainWindow", "ID"))
        self.treeWidget_oriHuffTbls.headerItem().setText(1, _translate("MainWindow", "Property"))
        self.treeWidget_oriHuffTbls.headerItem().setText(2, _translate("MainWindow", "Value"))
        self.btn_encrypt.setText(_translate("MainWindow", "Encrypt =>"))
        self.btn_saveToLibrary.setText(_translate("MainWindow", "Save to Library"))
        self.label_2.setText(_translate("MainWindow", "Encrypted"))
        self.lb_dstFilename.setText(_translate("MainWindow", "文件："))
        self.lb_dstSize.setText(_translate("MainWindow", "尺寸："))
        self.lb_dstImage.setText(_translate("MainWindow", "ImageLabel"))
        self.lb_dstComponents.setText(_translate("MainWindow", "颜色分量"))
        self.treeWidget_dstComponents.setSortingEnabled(False)
        self.treeWidget_dstComponents.headerItem().setText(0, _translate("MainWindow", "ID"))
        self.treeWidget_dstComponents.headerItem().setText(1, _translate("MainWindow", "Property"))
        self.treeWidget_dstComponents.headerItem().setText(2, _translate("MainWindow", "Value"))
        self.lb_dstQuantTbls.setText(_translate("MainWindow", "量化表"))
        self.treeWidget_dstQuantTbls.headerItem().setText(0, _translate("MainWindow", "ID"))
        self.treeWidget_dstQuantTbls.headerItem().setText(1, _translate("MainWindow", "Property"))
        self.treeWidget_dstQuantTbls.headerItem().setText(2, _translate("MainWindow", "Value"))
        self.lb_dstHuffTbls.setText(_translate("MainWindow", "哈夫曼表"))
        self.treeWidget_dstHuffTbls.headerItem().setText(0, _translate("MainWindow", "ID"))
        self.treeWidget_dstHuffTbls.headerItem().setText(1, _translate("MainWindow", "Property"))
        self.treeWidget_dstHuffTbls.headerItem().setText(2, _translate("MainWindow", "Value"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_addPhoto), _translate("MainWindow", "Add Photo"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "1"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "1"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "11"))
        self.treeWidget.topLevelItem(0).child(0).child(0).setText(0, _translate("MainWindow", "111"))
        self.treeWidget.topLevelItem(0).child(0).child(1).setText(0, _translate("MainWindow", "112"))
        self.treeWidget.topLevelItem(0).child(0).child(1).child(0).setText(0, _translate("MainWindow", "1121"))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "12"))
        self.treeWidget.topLevelItem(0).child(2).setText(0, _translate("MainWindow", "13"))
        self.treeWidget.topLevelItem(0).child(3).setText(0, _translate("MainWindow", "14"))
        self.treeWidget.topLevelItem(0).child(4).setText(0, _translate("MainWindow", "15"))
        self.treeWidget.topLevelItem(0).child(5).setText(0, _translate("MainWindow", "16"))
        self.treeWidget.topLevelItem(0).child(6).setText(0, _translate("MainWindow", "17"))
        self.treeWidget.topLevelItem(0).child(7).setText(0, _translate("MainWindow", "18"))
        self.treeWidget.topLevelItem(0).child(8).setText(0, _translate("MainWindow", "19"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("MainWindow", "2"))
        self.treeWidget.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "21"))
        self.treeWidget.topLevelItem(1).child(1).setText(0, _translate("MainWindow", "22"))
        self.treeWidget.topLevelItem(1).child(2).setText(0, _translate("MainWindow", "23"))
        self.treeWidget.topLevelItem(1).child(3).setText(0, _translate("MainWindow", "24"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Page"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setStatusTip(_translate("MainWindow", "Quit SecretPhotos"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setStatusTip(_translate("MainWindow", "Open file..."))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+F"))

from ImageLabel import ImageLabel
from AdaptiveTreeWidget import AdaptiveTreeWidget
