# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ui_MainWindow.ui'
#
# Created: Fri May 15 13:31:23 2015
#      by: PyQt5 UI code generator 5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1036, 712)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideMiddle)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_viewLibrary = QtWidgets.QWidget()
        self.tab_viewLibrary.setObjectName("tab_viewLibrary")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_viewLibrary)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(-1)
        self.horizontalLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btn_enterPassword = QtWidgets.QPushButton(self.tab_viewLibrary)
        self.btn_enterPassword.setObjectName("btn_enterPassword")
        self.horizontalLayout_6.addWidget(self.btn_enterPassword)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.scrollArea = QtWidgets.QScrollArea(self.tab_viewLibrary)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 964, 546))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.tab_viewLibrary, "")
        self.tab_addPhoto = QtWidgets.QWidget()
        self.tab_addPhoto.setObjectName("tab_addPhoto")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_addPhoto)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_loadImage = QtWidgets.QPushButton(self.tab_addPhoto)
        self.btn_loadImage.setAutoDefault(True)
        self.btn_loadImage.setDefault(True)
        self.btn_loadImage.setObjectName("btn_loadImage")
        self.horizontalLayout_3.addWidget(self.btn_loadImage)
        self.ckbox_scrollMode = QtWidgets.QCheckBox(self.tab_addPhoto)
        self.ckbox_scrollMode.setChecked(True)
        self.ckbox_scrollMode.setTristate(False)
        self.ckbox_scrollMode.setObjectName("ckbox_scrollMode")
        self.horizontalLayout_3.addWidget(self.ckbox_scrollMode)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.scrollArea_3 = ImageDetailScrollArea(self.tab_addPhoto)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 357, 544))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.horizontalLayout_5.addWidget(self.scrollArea_3)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.btn_encrypt = QtWidgets.QPushButton(self.tab_addPhoto)
        self.btn_encrypt.setEnabled(False)
        self.btn_encrypt.setObjectName("btn_encrypt")
        self.verticalLayout_5.addWidget(self.btn_encrypt)
        self.btn_decrypt = QtWidgets.QPushButton(self.tab_addPhoto)
        self.btn_decrypt.setEnabled(False)
        self.btn_decrypt.setObjectName("btn_decrypt")
        self.verticalLayout_5.addWidget(self.btn_decrypt)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_5.addItem(spacerItem3)
        self.btn_encryptEmb = QtWidgets.QPushButton(self.tab_addPhoto)
        self.btn_encryptEmb.setEnabled(False)
        self.btn_encryptEmb.setObjectName("btn_encryptEmb")
        self.verticalLayout_5.addWidget(self.btn_encryptEmb)
        self.btn_decryptExtract = QtWidgets.QPushButton(self.tab_addPhoto)
        self.btn_decryptExtract.setEnabled(False)
        self.btn_decryptExtract.setObjectName("btn_decryptExtract")
        self.verticalLayout_5.addWidget(self.btn_decryptExtract)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_5.addItem(spacerItem4)
        self.btn_saveToLibrary = QtWidgets.QPushButton(self.tab_addPhoto)
        self.btn_saveToLibrary.setEnabled(False)
        self.btn_saveToLibrary.setCheckable(False)
        self.btn_saveToLibrary.setFlat(False)
        self.btn_saveToLibrary.setObjectName("btn_saveToLibrary")
        self.verticalLayout_5.addWidget(self.btn_saveToLibrary)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem5)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.scrollArea_2 = ImageDetailScrollArea(self.tab_addPhoto)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 357, 544))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_5.addWidget(self.scrollArea_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.tabWidget.addTab(self.tab_addPhoto, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.treeWidget = AdaptiveTreeWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        self.treeWidget.setMinimumSize(QtCore.QSize(0, 100))
        self.treeWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_3 = QtWidgets.QTreeWidgetItem(item_2)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.verticalLayout_7.addWidget(self.treeWidget)
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit.setClearButtonEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_7.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_7.addWidget(self.pushButton)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem6)
        self.tabWidget.addTab(self.tab, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1036, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SecretPhotos"))
        self.btn_enterPassword.setText(_translate("MainWindow", "Enter Password"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_viewLibrary), _translate("MainWindow", "Library"))
        self.btn_loadImage.setText(_translate("MainWindow", "Load Photo..."))
        self.ckbox_scrollMode.setText(_translate("MainWindow", "synchronous scroll"))
        self.btn_encrypt.setText(_translate("MainWindow", "Encrypt =>"))
        self.btn_decrypt.setText(_translate("MainWindow", "Decrypt =>"))
        self.btn_encryptEmb.setText(_translate("MainWindow", "Encrypt && Emb message =>"))
        self.btn_decryptExtract.setText(_translate("MainWindow", "Decrypt && Extract message=>"))
        self.btn_saveToLibrary.setText(_translate("MainWindow", "Save to Library"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_addPhoto), _translate("MainWindow", "Add Photo"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "1"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "1"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "11"))
        self.treeWidget.topLevelItem(0).child(0).child(0).setText(0, _translate("MainWindow", "111"))
        self.treeWidget.topLevelItem(0).child(0).child(1).setText(0, _translate("MainWindow", "112"))
        self.treeWidget.topLevelItem(0).child(0).child(1).child(0).setText(0, _translate("MainWindow", "1121"))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "12"))
        self.treeWidget.topLevelItem(0).child(2).setText(0, _translate("MainWindow", "13"))
        self.treeWidget.topLevelItem(0).child(3).setText(0, _translate("MainWindow", "14"))
        self.treeWidget.topLevelItem(0).child(4).setText(0, _translate("MainWindow", "15"))
        self.treeWidget.topLevelItem(0).child(5).setText(0, _translate("MainWindow", "16"))
        self.treeWidget.topLevelItem(0).child(6).setText(0, _translate("MainWindow", "17"))
        self.treeWidget.topLevelItem(0).child(7).setText(0, _translate("MainWindow", "18"))
        self.treeWidget.topLevelItem(0).child(8).setText(0, _translate("MainWindow", "19"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("MainWindow", "2"))
        self.treeWidget.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "21"))
        self.treeWidget.topLevelItem(1).child(1).setText(0, _translate("MainWindow", "22"))
        self.treeWidget.topLevelItem(1).child(2).setText(0, _translate("MainWindow", "23"))
        self.treeWidget.topLevelItem(1).child(3).setText(0, _translate("MainWindow", "24"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Page"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setStatusTip(_translate("MainWindow", "Quit SecretPhotos"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setStatusTip(_translate("MainWindow", "Open file..."))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+F"))

from widgets.ImageDetailScrollArea import ImageDetailScrollArea
from widgets.AdaptiveTreeWidget import AdaptiveTreeWidget
