# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ui_MainWindow.ui'
#
# Created: Fri May 15 23:20:31 2015
#      by: PyQt5 UI code generator 5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1036, 712)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setElideMode(QtCore.Qt.ElideMiddle)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_viewLibrary = QtWidgets.QWidget()
        self.tab_viewLibrary.setObjectName("tab_viewLibrary")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_viewLibrary)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(-1)
        self.horizontalLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btn_enterPassword = QtWidgets.QPushButton(self.tab_viewLibrary)
        self.btn_enterPassword.setObjectName("btn_enterPassword")
        self.horizontalLayout_6.addWidget(self.btn_enterPassword)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.scrollArea = QtWidgets.QScrollArea(self.tab_viewLibrary)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 964, 546))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.tab_viewLibrary, "")
        self.tab_addPhoto = QtWidgets.QWidget()
        self.tab_addPhoto.setObjectName("tab_addPhoto")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_addPhoto)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_loadImage = QtWidgets.QPushButton(self.tab_addPhoto)
        self.btn_loadImage.setAutoDefault(True)
        self.btn_loadImage.setDefault(True)
        self.btn_loadImage.setObjectName("btn_loadImage")
        self.horizontalLayout_3.addWidget(self.btn_loadImage)
        self.ckbox_scrollMode = QtWidgets.QCheckBox(self.tab_addPhoto)
        self.ckbox_scrollMode.setChecked(True)
        self.ckbox_scrollMode.setTristate(False)
        self.ckbox_scrollMode.setObjectName("ckbox_scrollMode")
        self.horizontalLayout_3.addWidget(self.ckbox_scrollMode)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.scrollArea_ori = QtWidgets.QScrollArea(self.tab_addPhoto)
        self.scrollArea_ori.setWidgetResizable(True)
        self.scrollArea_ori.setObjectName("scrollArea_ori")
        self.saContents_ori = ImageDetailArea()
        self.saContents_ori.setGeometry(QtCore.QRect(0, 0, 395, 544))
        self.saContents_ori.setObjectName("saContents_ori")
        self.scrollArea_ori.setWidget(self.saContents_ori)
        self.horizontalLayout_5.addWidget(self.scrollArea_ori)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.btn_encrypt = QtWidgets.QPushButton(self.tab_addPhoto)
        self.btn_encrypt.setEnabled(False)
        self.btn_encrypt.setObjectName("btn_encrypt")
        self.verticalLayout_5.addWidget(self.btn_encrypt)
        self.btn_decrypt = QtWidgets.QPushButton(self.tab_addPhoto)
        self.btn_decrypt.setEnabled(False)
        self.btn_decrypt.setObjectName("btn_decrypt")
        self.verticalLayout_5.addWidget(self.btn_decrypt)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_5.addItem(spacerItem3)
        self.btn_encryptEmb = QtWidgets.QPushButton(self.tab_addPhoto)
        self.btn_encryptEmb.setEnabled(False)
        self.btn_encryptEmb.setObjectName("btn_encryptEmb")
        self.verticalLayout_5.addWidget(self.btn_encryptEmb)
        self.btn_decryptExtract = QtWidgets.QPushButton(self.tab_addPhoto)
        self.btn_decryptExtract.setEnabled(False)
        self.btn_decryptExtract.setObjectName("btn_decryptExtract")
        self.verticalLayout_5.addWidget(self.btn_decryptExtract)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_5.addItem(spacerItem4)
        self.lb_msg = QtWidgets.QLabel(self.tab_addPhoto)
        self.lb_msg.setObjectName("lb_msg")
        self.verticalLayout_5.addWidget(self.lb_msg)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_5.addItem(spacerItem5)
        self.btn_saveToLibrary = QtWidgets.QPushButton(self.tab_addPhoto)
        self.btn_saveToLibrary.setEnabled(False)
        self.btn_saveToLibrary.setCheckable(False)
        self.btn_saveToLibrary.setFlat(False)
        self.btn_saveToLibrary.setObjectName("btn_saveToLibrary")
        self.verticalLayout_5.addWidget(self.btn_saveToLibrary)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem6)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.scrollArea_dst = QtWidgets.QScrollArea(self.tab_addPhoto)
        self.scrollArea_dst.setWidgetResizable(True)
        self.scrollArea_dst.setObjectName("scrollArea_dst")
        self.saContents_dst = ImageDetailArea()
        self.saContents_dst.setGeometry(QtCore.QRect(0, 0, 394, 544))
        self.saContents_dst.setObjectName("saContents_dst")
        self.scrollArea_dst.setWidget(self.saContents_dst)
        self.horizontalLayout_5.addWidget(self.scrollArea_dst)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.tabWidget.addTab(self.tab_addPhoto, "")
        self.tab_comparePhoto = QtWidgets.QWidget()
        self.tab_comparePhoto.setObjectName("tab_comparePhoto")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_comparePhoto)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_loadOriImage = QtWidgets.QPushButton(self.tab_comparePhoto)
        self.btn_loadOriImage.setObjectName("btn_loadOriImage")
        self.horizontalLayout_2.addWidget(self.btn_loadOriImage)
        self.btn_loadCmpImage = QtWidgets.QPushButton(self.tab_comparePhoto)
        self.btn_loadCmpImage.setObjectName("btn_loadCmpImage")
        self.horizontalLayout_2.addWidget(self.btn_loadCmpImage)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.btn_compareImage = QtWidgets.QPushButton(self.tab_comparePhoto)
        self.btn_compareImage.setObjectName("btn_compareImage")
        self.horizontalLayout_2.addWidget(self.btn_compareImage)
        self.btn_saveCmpResult = QtWidgets.QPushButton(self.tab_comparePhoto)
        self.btn_saveCmpResult.setObjectName("btn_saveCmpResult")
        self.horizontalLayout_2.addWidget(self.btn_saveCmpResult)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lb_oriImage = ImageLabel(self.tab_comparePhoto)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_oriImage.sizePolicy().hasHeightForWidth())
        self.lb_oriImage.setSizePolicy(sizePolicy)
        self.lb_oriImage.setMinimumSize(QtCore.QSize(300, 300))
        self.lb_oriImage.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_oriImage.setObjectName("lb_oriImage")
        self.horizontalLayout_4.addWidget(self.lb_oriImage)
        self.lb_cmpImage = ImageLabel(self.tab_comparePhoto)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_cmpImage.sizePolicy().hasHeightForWidth())
        self.lb_cmpImage.setSizePolicy(sizePolicy)
        self.lb_cmpImage.setMinimumSize(QtCore.QSize(300, 300))
        self.lb_cmpImage.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_cmpImage.setObjectName("lb_cmpImage")
        self.horizontalLayout_4.addWidget(self.lb_cmpImage)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.tabWidget.addTab(self.tab_comparePhoto, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1036, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SecretPhotos"))
        self.btn_enterPassword.setText(_translate("MainWindow", "Enter Password"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_viewLibrary), _translate("MainWindow", "Library"))
        self.btn_loadImage.setText(_translate("MainWindow", "Load Photo..."))
        self.ckbox_scrollMode.setText(_translate("MainWindow", "synchronous scroll"))
        self.btn_encrypt.setText(_translate("MainWindow", "Encrypt =>"))
        self.btn_decrypt.setText(_translate("MainWindow", "Decrypt =>"))
        self.btn_encryptEmb.setText(_translate("MainWindow", "Encrypt && Emb \n"
"message =>"))
        self.btn_decryptExtract.setText(_translate("MainWindow", "Decrypt && Extract \n"
"message =>"))
        self.lb_msg.setText(_translate("MainWindow", "TextLabel"))
        self.btn_saveToLibrary.setText(_translate("MainWindow", "Save to Library"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_addPhoto), _translate("MainWindow", "Add Photo"))
        self.btn_loadOriImage.setText(_translate("MainWindow", "Load Original \n"
"Image"))
        self.btn_loadCmpImage.setText(_translate("MainWindow", "Load Compared \n"
"Image"))
        self.btn_compareImage.setText(_translate("MainWindow", "Compare"))
        self.btn_saveCmpResult.setText(_translate("MainWindow", "Save Compare"))
        self.lb_oriImage.setText(_translate("MainWindow", "Original Image Label"))
        self.lb_cmpImage.setText(_translate("MainWindow", "Compared Image Label"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_comparePhoto), _translate("MainWindow", "Compare Photo"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setStatusTip(_translate("MainWindow", "Quit SecretPhotos"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setStatusTip(_translate("MainWindow", "Open file..."))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+F"))

from widgets.ImageLabel import ImageLabel
from widgets.ImageDetailArea import ImageDetailArea
